apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      serviceName: mysql
      replicas: 1
      selector:
        matchLabels:
          name: mysql
      restartPolicy: Always
      containers:
      - name: mysql
        image: mysql:5.7.36
        imagePullPolicy: IfNotPresent
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
          subPath: data
        - mountPath: /etc/mysql/conf.d
          name: mysql-data
          subPath: conf.d
        env: {{ $envList := list }}
        {{ $secretName := "mysqlsecret" }}
        {{ $envList = mustAppend $envList (dict "name" "MYSQL_ROOT_PASSWORD" "valueFromSecret" true "secretName" $secretName "secretKey" "root-password") }}
        {{ include "common.containers.environmentVariables" (dict "environmentVariables" $envList) | nindent 10 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
