apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:5.7.36
          imagePullPolicy: IfNotPresent
          env:
            MYSQL_ROOT_PASSWORD: "{{ .Values.rootpassword }}"
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
              subPath: data
            - mountPath: /etc/mysql/conf.d
              name: mysql-data
              subPath: conf.d
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0