apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: 
    name: mysql
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels: 
      name: mysql
  serviceName: mysql
  template:
    metadata:
      labels: 
        name: mysql
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: mysql:5.7.36
        imagePullPolicy: IfNotPresent
        ports:
        - name: mysql
          containerPort: 3306
          hostPort: 3306
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
          subPath: data
        - mountPath: /etc/mysql/conf.d
          name: mysql-data
          subPath: conf.d
        env: {{ $envList := (default list .Values.environmentVariables) }}
        {{ $envList = mustAppend $envList (dict "name" "MYSQL_ROOT_PASSWORD" "value" .Values.rootpassword) }}
        {{ include "common.containers.environmentVariables" (dict "environmentVariables" $envList) | nindent 12 }}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate