apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mariadb-password: {{ ( .Values.postgresqlPassword | default "empty" ) | b64enc | quote }}
  mariadb-root-password: {{ ( .Values.postgrespassword | default "empty" ) | b64enc | quote }}
