apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.rootpassword | b64enc | quote }}