apiVersion: v2
appVersion: '23'
dependencies:
- name: common
  repository: file://../../../library/common/2105.0.0
  version: 2105.0.0
description: nextcloud
home: https://nextcloud.com/
icon: https://github.com/XSana/truenas-chart/blob/main/icon/nextcloud.svg?raw=true
keywords:
- nextcloud
name: nextcloud
sources:
- https://github.com/nextcloud/docker
version: 0.0.8
