apiVersion: v2
appVersion: "5.7.36"
name: mysql
description: MySQL 5.7.36
type: application
version: 0.2.9
kubeVersion: '>=1.16.0-0'
dependencies:
- name: common
  repository: file://../../../library/common/2105.0.0
  version: 2105.0.0
home: https://www.mysql.com
icon: https://github.com/XSana/truenas-chart/blob/main/icon/mysql-logo.png?raw=true
keywords:
- mysql
- database
- sql
sources:
- https://github.com/mysql/mysql-server